#ifndef FLIP_MODEL_H
#define FLIP_MODEL_H

#include <QObject>
#include <QString>
#include <QMap>

class FlipModel : public QObject {
    Q_OBJECT
public:
    enum Language {
            NoLanguage = -1,
            Auto,
            Afrikaans,
            Albanian,
            Amharic,
            Arabic,
            Armenian,
            Azerbaijani,
            Bashkir,
            Basque,
            Belarusian,
            Bengali,
            Bosnian,
            Bulgarian,
            Cantonese,
            Catalan,
            Cebuano,
            Chichewa,
            Corsican,
            Croatian,
            Czech,
            Danish,
            Dutch,
            English,
            Esperanto,
            Estonian,
            Fijian,
            Filipino,
            Finnish,
            French,
            Frisian,
            Galician,
            Georgian,
            German,
            Greek,
            Gujarati,
            HaitianCreole,
            Hausa,
            Hawaiian,
            Hebrew,
            HillMari,
            Hindi,
            Hmong,
            Hungarian,
            Icelandic,
            Igbo,
            Indonesian,
            Irish,
            Italian,
            Japanese,
            Javanese,
            Kannada,
            Kazakh,
            Khmer,
            Kinyarwanda,
            Klingon,
            KlingonPlqaD,
            Korean,
            Kurdish,
            Kyrgyz,
            Lao,
            Latin,
            Latvian,
            LevantineArabic,
            Lithuanian,
            Luxembourgish,
            Macedonian,
            Malagasy,
            Malay,
            Malayalam,
            Maltese,
            Maori,
            Marathi,
            Mari,
            Mongolian,
            Myanmar,
            Nepali,
            Norwegian,
            Oriya,
            Papiamento,
            Pashto,
            Persian,
            Polish,
            Portuguese,
            Punjabi,
            QueretaroOtomi,
            Romanian,
            Russian,
            Samoan,
            ScotsGaelic,
            SerbianCyrillic,
            SerbianLatin,
            Sesotho,
            Shona,
            SimplifiedChinese,
            Sindhi,
            Sinhala,
            Slovak,
            Slovenian,
            Somali,
            Spanish,
            Sundanese,
            Swahili,
            Swedish,
            Tagalog,
            Tahitian,
            Tajik,
            Tamil,
            Tatar,
            Telugu,
            Thai,
            Tongan,
            TraditionalChinese,
            Turkish,
            Turkmen,
            Udmurt,
            Uighur,
            Ukrainian,
            Urdu,
            Uzbek,
            Vietnamese,
            Welsh,
            Xhosa,
            Yiddish,
            Yoruba,
            YucatecMaya,
            Zulu
        };
        Q_ENUM(Language)

    void translate(Language from, Language to, QString sentece);

signals:
    void translated(QString translatedSentence);

private:
    static const QMap<Language, QString> languageToCode;
    QString APIUrl = "https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl=%1&tl=%2&dt=t&q=%3";

private slots:
    void translateFinished();
};

#endif //FLIP_MODEL_H
